<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
const props = defineProps({ values:{type:Array,default:()=>[]}, labels:{type:Array,default:()=>[]}, min:Number, max:Number, mode:{type:String,default:'2d'} })
const canvas=ref(null);let observer
const coords=[[-.02,-.72],[-.58,-.46],[.0,-.4],[.55,-.45],[-.72,-.05],[0,-.02],[.7,-.04],[-.52,.3],[.12,.34],[.63,.3],[-.48,.68],[0,.72],[.48,.65]]
function valueAt(x,y){let sum=0,w=0;coords.forEach(([px,py],i)=>{const d=Math.max(.035,(x-px)**2+(y-py)**2);const k=1/d;sum+=(props.values[i]??0)*k;w+=k});return sum/Math.max(w,1)}
function color(v){const t=Math.max(0,Math.min(1,(v-props.min)/Math.max(1,props.max-props.min)));const stops=[[31,69,230],[16,190,220],[56,214,132],[244,225,52],[249,128,34],[220,38,38]];const p=t*(stops.length-1),a=Math.floor(p),b=Math.min(stops.length-1,a+1),f=p-a;return `rgb(${stops[a].map((n,j)=>Math.round(n+(stops[b][j]-n)*f)).join(',')})`}
function draw2d(ctx,w,h){const size=Math.min(w,h)-42,cx=w/2,cy=h/2,r=size/2;const off=document.createElement('canvas');off.width=120;off.height=120;const oc=off.getContext('2d'),img=oc.createImageData(120,120);for(let y=0;y<120;y++)for(let x=0;x<120;x++){const nx=(x-60)/57,ny=(y-60)/57,idx=(y*120+x)*4;if(nx*nx+ny*ny<=1){const c=color(valueAt(nx,ny)).match(/\d+/g).map(Number);img.data.set([...c,255],idx)}}oc.putImageData(img,0,0);ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.clip();ctx.imageSmoothingEnabled=true;ctx.drawImage(off,cx-r,cy-r,size,size);ctx.restore();ctx.strokeStyle='#173f88';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();coords.forEach(([x,y],i)=>{const px=cx+x*r*.88,py=cy+y*r*.88;ctx.fillStyle='#fff';ctx.strokeStyle='#263b70';ctx.lineWidth=1.3;ctx.beginPath();ctx.arc(px,py,4,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#20374b';ctx.font='700 10px sans-serif';ctx.textAlign='center';ctx.fillText(props.labels[i]||`S${i+1}`,px,py-8)})}
function project(x,y,z,w,h){return [w*.5+(x-y)*w*.23,h*.66+(x+y)*h*.11-z*h*.23]}
function draw3d(ctx,w,h){const n=24,base=props.min,span=Math.max(1,props.max-props.min);ctx.strokeStyle='#dce4ee';ctx.lineWidth=1;for(let i=-1;i<=1;i+=.25){let a=project(-1,i,0,w,h),b=project(1,i,0,w,h);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();a=project(i,-1,0,w,h);b=project(i,1,0,w,h);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}for(let yi=n-2;yi>=0;yi--)for(let xi=0;xi<n-1;xi++){const pts=[];[[xi,yi],[xi+1,yi],[xi+1,yi+1],[xi,yi+1]].forEach(([gx,gy])=>{const x=-1+gx*2/(n-1),y=-1+gy*2/(n-1),inside=x*x+y*y<=1.02,z=(valueAt(x,y)-base)/span;pts.push({p:project(x,y,z,w,h),v:valueAt(x,y)})});if(pts.every(p=>p.p)){ctx.fillStyle=color(pts.reduce((s,p)=>s+p.v,0)/4);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.beginPath();ctx.moveTo(...pts[0].p);pts.slice(1).forEach(p=>ctx.lineTo(...p.p));ctx.closePath();ctx.fill();ctx.stroke()}}ctx.strokeStyle='#173f88';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<=64;i++){const a=i/64*Math.PI*2,p=project(Math.cos(a),Math.sin(a),0,w,h);i?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.stroke()}
function draw(){const c=canvas.value;if(!c)return;const rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,rect.width,rect.height);props.mode==='2d'?draw2d(ctx,rect.width,rect.height):draw3d(ctx,rect.width,rect.height)}
watch(()=>[props.values,props.min,props.max,props.mode],()=>nextTick(draw),{deep:true});onMounted(()=>{observer=new ResizeObserver(draw);observer.observe(canvas.value);draw()});onBeforeUnmount(()=>observer?.disconnect())
</script>
<template><canvas ref="canvas"></canvas></template>
<style scoped>canvas{display:block;width:100%;height:315px;background:#fff;border-radius:10px}</style>
